### PR TITLE
Nick management

### PR DESCRIPTION
**Pull request by Raia**

### CODE REVIEW

**Comment by McInkay** [comment]
@Raia What's up with this just now, from your point of view, is it needing work or is it ready for review? I was wanting this functionality, and just noticed you had it in this PR. Need any help just now?

**Comment by McInkay** [comment]
Oh wait, how does this change from Alias? Just noticed it's using "Nick" table. Don't think that exists anywhere yet, is it different from Alias?

**Comment by Raia** [comment]
We weren't sure how to handle the permissions and who should be able to add/remove names, so this got super stale because we never figured it out.

The `Nick` table changed to `Alias` because an alias isn't necessarily a registered nick. Before, we used to assume that any given alias was a valid nick that person might use, and since that wasn't true in like 90% of cases that was kind of a security issue.

**Comment by McInkay** [comment]
Alright, so it's quite old then. I'll probably rewrite as I'm rewriting most of the db stuff and that's most of this.

**Comment by Raia** [comment]
Sounds good, I'll go ahead and close this then :+1:

**Pull request closed without merging**
