### PR TITLE
Make highfive properly case insensitive

### LINKED ISSUE #72: Capital O in O/ breaks other high fives
It seems to act as a `\o` but I'm not sure?

### PR DESCRIPTION
**Pull request by McInkay**
Fixes #72

### CODE REVIEW

**Comment by Raia** [comment]
Thanks for the fix @YaManicKill! But hmm...

```
23:29:21 <~Raia>  o/
23:29:22 <~Raia>  \o
23:29:22 <Porygon-Bot>  Raia o/\o Raia
23:29:22 <Jellicent-Bot>  Raia o/\o Raia
23:29:27 <~Raia>  O/
23:29:28 <~Raia>  \o
23:29:28 <Jellicent-Bot>  Raia o/\o Raia
23:29:32 <~Raia>  o/
23:29:33 <Porygon-Bot>  Raia o/\o Raia
23:29:38 <~Raia>  O/
23:29:42 <~Raia>  \O
23:29:48 <~Raia>  o/
23:29:48 <Porygon-Bot>  Raia o/\o Raia
23:29:48 <Jellicent-Bot>  Raia o/\o Raia
23:29:50 <~Raia>  \o
```

I think I'd have expected one more successful pairing out of that.

Maybe we should just kill `O/` and make it not count?

**Comment by YaManicKill** [comment]
Ah no, I know what the issue is with that, there's a check I missed. Will look at it later.

**Comment by YaManicKill** [comment]
Aight, that should fix it. There were a few checks where we just checked the pure text `o/` or `\o` which was causing the problem. More regex was the fix, obv.

**Comment by McInkay** [comment]
@Raia Any chance to check if you are happy with this now? It should fix the issue you mentioned before.

**Pull request merged**
