### PR TITLE
Move to irc-fw

### PR DESCRIPTION
**Pull request by AlMcKinlay**
Node irc hasn't been touched in 2 years, and it uses node-gyp which causes some real issues when installing on some machines. We use irc-framework on the lounge and it's great.

This will need some proper testing to make sure that I've not messed anything up.

### CODE REVIEW

**Comment by McInkay** [comment]
Ok, I think this is the last one before #69 and I'll just start working on the stuff only I want. 

Let me know whether people actually want this or not. If not, I'll close the PR, but if so, we just need someone to spin up a bot from this code with the config that @Raia uses, and we can test it on the testing channel to make sure there's nothing that I missed.

I did a bunch of testing myself, but we need a person or 2 to double check stuff. It shouldn't take too much work at all. I'm happy to spin up the bot with the config if someone can pass me to it, and then a bunch of you can just run commands in the channel to make sure I didn't miss anything.

I'd really love to get this in so I can finish off the stuff I was doing on it.

**Comment by McInkay** [comment]
Nudge

**Comment by McInkay** [comment]
Monthly nudge.

**Comment by AlMcKinlay** [comment]
Anyone?

**Pull request closed without merging**
